services:
  sonarr-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonarr-mcp
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
    ports:
      - "${SONARR_MCP_PORT:-9171}:9171"
    env_file:
      - .env
    volumes:
      - /mnt/cache/appdata/sonarr-mcp/logs:/app/logs
    networks:
      - jakenet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9171/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  jakenet:
    external: true

