services:
  sonarr-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonarr-mcp-server
    restart: unless-stopped
    ports:
      - "${SONARR_MCP_PORT:-9171}:9171"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - sonarr-mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9171/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sonarr-mcp-network:
    driver: bridge